version: 2

updates:
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
    groups:
      actions:
        patterns:
          - "*"

  - package-ecosystem: github-actions
    directory: /actions/setup-pnpm
    schedule:
      interval: weekly
    groups:
      actions:
        patterns:
          - "*"

  - package-ecosystem: github-actions
    directory: /actions/setup-bun
    schedule:
      interval: weekly
    groups:
      actions:
        patterns:
          - "*"
